### ISSUE TITLE
Audio Slowly Desync's in Teleport

### ISSUE THREAD

**Issue by icefire555** [fzwoch/obs-teleport#107] opened 2024-12-01 20:04 UTC
Issue:
My last stream shows this issue pretty well. The audio slowly desync's. What's more odd is that all my audio is being transmit in different channels and this only happens when I play Call Of Duty Black Ops 6.
https://www.twitch.tv/videos/2315334578

The start of this video shows everything is synced. But by 1hr 40m you can visually see the gun firing desynced from the shooting sounds. 
https://www.twitch.tv/videos/2315334578?t=01h40m24s

And near the end there is quite a desync.
https://www.twitch.tv/videos/2315334578?t=03h29m22s

This stream shows this issue at an extreme. 
I noticed after compiling shaders in Cod the audio was very desynced. It's possible CPU usage is causing this issue.
https://youtu.be/AE9tj1RNjj8?t=125

I Disable and Re-Enable Teleport on the Game Pc at this point in that Vod. (Through the Tools > Teleport > Teleport Enabled Checkbox)
https://youtu.be/AE9tj1RNjj8?t=6501

Setup:
I have a Game PC running OBS only to teleport audio.
Each Audio source is being sent over to my Stream pc.
I have 4 audio sources in total. Discord, My Mic (For subtitles), My System Audio (The Game), And my browser audio (for music separation on a vod track). My game capture is being handled via a capture card.

Each Teleport is set to 90% quality and I'm not trying to send any video to the other computer to try and limit usage.
Both Pcs are wired to my network.

Game PC Hardware:
AMD 9950x
RTX 4090
96GB ram

Stream Pc:
Intel i9-13980HX
RTX 4070 Laptop
16GB ram

Mitigation:
If I disable Teleport on my stream pc and re-enable it, it syncs back up and the issue seems to reset.

**Comment by johnvo0918** [comment] 2024-12-02 05:34
Suffering the same issue here. I've reinstalled OBS and match teleport version, yet it still desync randomly. I tried streaming with logs on and randomly it will say "audio buffering added into audio source, usually 175ms" or something like that. Like OP said, if I disable teleport and turn it back on, it will fix itself.
Not sure if this is the same problem but sometimes the teleported audio will also become very buzzy, the best fix is again, turning it off and on.

**Comment by fzwoch** [comment] 2024-12-02 08:43
The only way you kind of have control over sync is by using a Teleport stream that is sending audio and video. Parallel streams stand by there own and there is no way to sync these instances to each other.

You can also try to hide the Teleport source on the receiver, wait a few seconds and unhide it. If then sync is back it is entirely on the OBS side when these streams are rendered. A plugin is almost no control over it.

**Comment by fzwoch** [comment] 2024-12-02 15:02
There is no guarantee about the sync in this case. I also do not know about a better way. Usually OBS decides to increase the latency of this stream if the data starves, so it may be an indication of a longer network congestion.

The buzzing sound sounds like a bug, e.g some data is being dropped and it was not properly aligned. I never experienced this in my tests though, so I would need something I can reproduce reliably.

**Comment by YorVeX** [comment] 2024-12-02 19:02
It's a known problem that OBS has a variable delay for its sources. One thing that is meant as an attempt to solve this and you could try and which might not be obvious from the description is checking this option:
![image](https://github.com/user-attachments/assets/67016ae5-b60f-4d74-8eb7-6aa554b0ee68)

I personally had mixed results with it, e.g. in a certain setup it caused other issues like audio distortions for me, but it sure is worth a shot.

Speaking of audio distortions, on which Windows version are you? There is a known issue in Windows that causes audio issues after longer run times, and it was fixed only recently in a newer feature release of Windows 11, see [this issue](https://github.com/obsproject/obs-studio/issues/8064).

**Comment by icefire555** [comment] 2024-12-02 19:20
That's an interesting thing to try @YorVeX, I'm hoping that with the stable networking it shouldn't cause much in distortions. 
If that causes unpleasant side effects I'll give beam a try. I appreciate the alternative option! A constant delay is easier to work with.

My concern with VBAN which may not be relevant because I don't know how it works yet. Would be extra audio devices in windows. Windows loves to pick the wrong device so I try to keep my setup as simple as I can for what I'm doing. I will look into it if the other options don't pan out.

In an ideal world I would love to just use cables to route audio between the Pcs, but the 4 channels makes the setup a little janky. and without separation I can't easily get closed captions working.

I don't hear any audio issues like johnvo0918 mentioned, just the delay. I actually have a multi gigabit network using mikrotik network devices. 

My Game Pc and Stream Pc are running Windows 11 23H2 (22631.4460) based on what about my PC states on both computers. "Windows Feature Experience Pack 1000.22700.1047.0"

**Comment by fzwoch** [comment] 2024-12-03 07:22
Thanks @YorVeX for the link about the audio issue on Windows. I didn't  know about it.

Will be closing this as I feel there is no bug here, more limitations in the context of how OBS works.

Beam is always a nice alternative, too bad it has no macOS support ;-)

**Closed by fzwoch** 2024-12-03 07:22 UTC

**Comment by icefire555** [comment] 2024-12-10 18:29
A quick update to this for anyone that sees this later.

So far I've tried the OBS setting to no luck.

I've also tried beam, but it appears to desync at a much faster speed than teleport and it restarts the session often even at a 1000ms delay. Beam also doesn't seem to work as it should. The select a stream feature does not work at all for me and I have to manually set the IP and port for it to function. Even then it doesn't show a stream but I can see it sending audio over. This is also only sending audio, task manager shows 10mbit of data being sent.

Later I'm going to look at my laptop to see if it has QoS on it's network port via software as the network the connection runs over is 10gbit to the switch, but 1gbit to the laptop on the last switch. So there shouldn't be any bottlenecking.

**Comment by YorVeX** [comment] 2024-12-10 19:19
> A quick update to this for anyone that sees this later.
> 
> So far I've tried the OBS setting to no luck.
> 
> I've also tried beam, but it appears to desync at a much faster speed than teleport and it restarts the session often even at a 1000ms delay. Beam also doesn't seem to work as it should. The select a stream feature does not work at all for me and I have to manually set the IP and port for it to function. Even then it doesn't show a stream but I can see it sending audio over. This is also only sending audio, task manager shows 10mbit of data being sent.
> 
> Later I'm going to look at my laptop to see if it has QoS on it's network port via software as the network the connection runs over is 10gbit to the switch, but 1gbit to the laptop on the last switch. So there shouldn't be any bottlenecking. 
> 
> I don't want to use VBAN because I need my pc for work and don't want a more complex audio setup for non-stream time. It will be my last ditch effort.

That sounds like you didn't configure Beam correctly. Happy to help with this but we shouldn't do that here on an issue for Teleport, feel free to either open an issue on the Beam GitHub so we can continue the discussion there, or dm me on Discord (@yorvex).

**Comment by Francesco149** [comment] 2024-12-27 02:26
I'm just gonna add my personal experience and workaround with this:

I have a windows laptop with a stripped down obs + teleport and a linux streaming pc receiving the video from teleport.

the obs on the laptop is being started on logon through a scheduled task, running as admin.

teleport source becomes severely delayed by 500+ms over 30min-1hr (not desynced from audio, just increasingly delayed overall).

I found that if I manually restart the obs on the laptop (running as admin still) it fixes the issue for whatever reason and I get a nice non-delayed stream for many hours no problem. so I suspect it's some kind of janky cpu scheduling issue that is caused by the task scheduler starting obs.

the cpu on that laptop is a i5-1335u so not super high end but enough to get a smooth teleport feed and record when needed

**Comment by icefire555** [comment] 2024-12-27 02:38
@Francesco149 I wonder if a tool like processlasso could set OBS to use unused cores and if it would help.

**Comment by fzwoch** [comment] 2024-12-27 08:46
> teleport source becomes severely delayed by 500+ms over 30min-1hr (not desynced from audio, just increasingly delayed overall).
> 
> I found that if I manually restart the obs on the laptop (running as admin still) it fixes the issue for whatever reason and I get a nice non-delayed stream for many hours no problem. so I suspect it's some kind of janky cpu scheduling issue that is caused by the task scheduler starting obs.

This is up to OBS when to play the data. Usually it is a lag (probably caused by network) and OBS delays playing of that data as it doeas not try to catch up to maintain the original timing. Thats the reason Beam likes to add a very high latency, so lags fit into this latency preventing running into this OBS behavior.

You don't even have to stop/start, but just hiding the Teleport source for 2 to 3 seconds and then unhide it again should give you a standard latency again. Teleport keeps running normally during this time. OBS just discovers a big gap and resync the stream again.

A plugin does not get info on those states of OBS unfortunately, so no real countermeasures can be done. (Other than just adding a huge buffer/delay to begin with and crossing your fingers your stalls never exceed this buffer)

**Comment by Francesco149** [comment] 2024-12-27 12:30
the interesting thing is that if I just deselect and reselect the teleport source it becomes delayed again very quickly, but if I completely restart the obs that's sending the video it's fixed for hrs. so something about the first instance of obs is making it fall behind more easily. prob process priority/scheduling stuff idk but this workaround has been pretty consistent for me

**Comment by fzwoch** [comment] 2024-12-27 16:41
What does mean deselect and reselect here exactly?

**Comment by Francesco149** [comment] 2024-12-27 16:57
> What does mean deselect and reselect here exactly?

on the teleport source on the streaming pc. select nothing and then re-select the teleport stream.

anwyay, manually starting obs as admin after starting the game reliably works to not have any latency

**Comment by icefire555** [comment] 2024-12-31 17:32
> the interesting thing is that if I just deselect and reselect the teleport source it becomes delayed again very quickly, but if I completely restart the obs that's sending the video it's fixed for hrs. so something about the first instance of obs is making it fall behind more easily. prob process priority/scheduling stuff idk but this workaround has been pretty consistent for me

This did nothing for me on the sender side. I think the reset has to happen on the receiver.

**Comment by YorVeX** [comment] 2025-01-03 03:45
> teleport source becomes severely delayed by 500+ms over 30min-1hr (not desynced from audio, just increasingly delayed overall).

That's normal and just happens as a result of how OBS handles syncing audio and video for itself and its sources and outputs, based on timestamps. The timestamps between video and audio can go out of sync for various reasons (more on this below), but as long as everything happens locally, OBS will keep track of the difference and still sync it properly to the main feed. And more importantly: process it directly without delays.

The story changes when a source or output takes its audio and video frames and sends it to a remote OBS, and then another source wants to feed this data there into the remote OBS. The timestamp data is still there, but the remote OBS doesn't know about the syncing information of the sender OBS and interprets them differently, e.g. when it sees audio is 500 ms behind video in the data that is ingested there based on the timestamps, it will delay the whole feed by 500 ms to make it match. So audio and video are in sync on the receiver side, but the whole feed is now delayed by 500 ms.

That's just one simplified example, there is more going on about the timestamp syncing, but the point is, the timestamps and syncing mechanism in OBS were never meant to be used in a remote OBS, but that's what NDI, Teleport and Beam have to do, because it's all they get from OBS.

Reason number 1 why those desyncs occur are lags on the sender side. You can get tiny ones that a human doesn't notice but that over time will accumulate to a bigger delay, and you can get bigger ones, that will also cause an immediate delay on the receiver side.

> 
> I found that if I manually restart the obs on the laptop (running as admin still) it fixes the issue for whatever reason and I get a nice non-delayed stream for many hours no problem. so I suspect it's some kind of janky cpu scheduling issue that is caused by the task scheduler starting obs.

For the reason I've given, CPU scheduling and load in general can definitely have an impact. Having your system run as smooth as possible will help to avoid this issue. And when you restart, many things that initially had to be loaded are now cached in the system (both in OBS and content that you stream/record) and lags are a lot less likely.

Whether for an individual this can be a solution holding up for 10 minutes, an hour, 2 hours or 8 depends a lot on what they do with the system. If you do something that causes very consistent and minimal load, chances are good that you're fine for a long time. Also how often you do things in OBS plays a role, e.g. how often you change scenes, how many special effects and transitions you have and so on.

Unfortunately that means there are conditions where it's impossible to avoid these lags. Some games just suck up even the most beefy system when loading a level/map or loading initially, add a complex OBS setup with lots of scene changes and transitions and effects and I bet even a 9800X3D will not keep a stable sync for long.

And if you want to see something funny: add a simple image source to your sender OBS and use it to load a large image file (several megs, maybe you have a wallpaper image that big you could use). Be sure to check "Unload image when not showing". Now while having a NDI/Teleport/Beam feed (really doesn't matter), toggle visibility of that source a few times and watch the sync/delay on the receiver side 😄

**Comment by icefire555** [comment] 2025-01-03 04:51
@YorVeX, Right now I'm trying to use a Capture Card with teleport. Are you suggesting if I capture Audio and Video on the Output it should stay synced since they are being collected and send from the same system? 

If not, is there any situation this would work?

**Comment by YorVeX** [comment] 2025-01-03 04:57
I am not really familiar with using capture cards myself, but since their timestamps are not generated by OBS, there should be a good chance you don't have the same kind of issue there.

**Comment by YorVeX** [comment] 2025-01-03 05:01
Oh, wait, I misread and thought you wanted to use the capture card for everything. For that mix there is actually a chance it's working, as long as you send a video only filter based feed from Teleport or Beam (don't use an output). For video only feeds OBS also doesn't apply the same syncing mechanisms. But it really needs to be explicitly video only.

**Comment by icefire555** [comment] 2025-01-03 21:03
@YorVeX Would it be easier to keep things Synced using only teleport? And is there any way to keep the separate Teleport Audio Senders in sync? Or do you know of anything that I could read up on to better understand how the sync timestamp system works in OBS? I feel bad asking for your help on this.

Earlier I did a test where I has the main Teleport output and a separate audio channel teleport and over the course of 3 hours the separate audio channel lost about 8 frames of sync. (Not bad, but it will get worse) 
> If there isn't a proper method, I might be able to hotkey a swap over where I hide the separate channels to reset them and swap to the main one for a few seconds then swap back. 

I saw an option to include audio timestamps on the sound devices. I just don't think it impacted anything for this issue.
![image](https://github.com/user-attachments/assets/3bb69baa-6ece-473b-b91b-711f7e6d4b24)

A couple key points to explain:
- The main Teleport output is working great, the audio and video seems to stay synced which is amazing! My only gripe is it's 1 audio feed which isn't the end of the world. But it removes my ability to use a Twitch Vod Track to avoid copyright strikes.

- The capture card has to have both video and audio, I didn't see an option to remove it in OBS, only tell it to use a system audio device. I'm indifferent if it's used because it struggles to capture well. Its an elgato 4k x. and at 4k the video looks awful. I have to run it at 1440p to not have awful frame timing on the capture.
(The resolution is set low because I'm not using the video capture from it)
![image](https://github.com/user-attachments/assets/d25c3c66-5c66-47f5-b0a5-2968c9fe3436)
- I'm ordering a 3.5mm cable to remove the capture card from the setup. I'm happy to use it. But I far prefer synced audio at this point over video capture from it. And the teleport video is very high quality for the fairly limited computer impact.

- I'm a vtuber so majority of my 2 pc setup need is that 2 pieces of software run on like 30% of the cpu. So moving it off the pc is a big benefit.

**Comment by fzwoch** [comment] 2025-01-03 23:26
Sounds like Beam needs multi-track support! :dagger:

**Comment by YorVeX** [comment] 2025-01-04 04:29
> @YorVeX Would it be easier to keep things Synced using only teleport? And is there any way to keep the separate Teleport Audio Senders in sync? Or do you know of anything that I could read up on to better understand how the sync timestamp system works in OBS? I feel bad asking for your help on this.

If you keep video and audio within one feed (simply using the Teleport output that contains both):
1) Video and Audio will in relation to each other stay in sync, you will not get A/V desync, which is good.
1) The delay between sender OBS and receiver OBS will, however, not be consistent, as explained in my earlier comment. It will increase slowly over time or have sudden increases when lags occur. A typical curve from my tests is that it keeps going up until it reaches around 800-1000 ms, then goes down again and stays at smaller swings around 400-600 ms, but ofc YMMV depending on the setup.

If all you have is that one combined audio and video feed, 2 will not be an issue, not even in a live stream, with the delay being as small as that.
 
> Earlier I did a test where I has the main Teleport output and a separate audio channel teleport and over the course of 3 hours the separate audio channel lost about 8 frames of sync. (Not bad, but it will get worse)

Exactly. As soon as you try to sync another separate audio and video feed to your combined video and audio feed from OBS, 2 will suddenly become an issue. You can artificially delay that separate feed, but what delay do you pick? In the beginning 33-66 ms would be right, 1000 ms at a later point, then 500 ms again.

For simplicity, let's just give the frames simple numbers instead of timestamps, counting up from 1. At some point, your primary output feed will get delayed by a frame. Video and audio of that feed will be kept in sync to each other, but any secondary audio feed would not have that delay and therefore not be in sync to the primary feed:
```
Primary Video:   2 - 3 - 4 - 5 - 6
Primary Audio:   2 - 3 - 4 - 5 - 6
Secondary Audio: 1 - 2 - 3 - 4 - 5

```

> If there isn't a proper method, I might be able to hotkey a swap over where I hide the separate channels to reset them and swap to the main one for a few seconds then swap back.

Resetting them should pretty reliably reset the delay to the original 33-66 ms. Whether regularly doing that is an option for you, depends on how fast the delay increases for you. If it takes an hour to get to the point where it's noticeable, and you don't mind resetting every hour, then that would be a simple workaround, and I've seen people state that this is what they've been doing for a long time.
When I had the same issues in my own streams and Beam didn't exist yet, I even had a chat command that my mods could use to reset it, when they noticed it would get desync. If you regularly take breaks with a BRB scene, this would also be a good point to do the reset, or while running an ad for people.

> I saw an option to include audio timestamps on the sound devices. I just don't think it impacted anything for this issue.

You can ignore that, doesn't help with the issues we're having here.

> 
> A couple key points to explain:
> 
> * The main Teleport output is working great, the audio and video seems to stay synced which is amazing! My only gripe is it's 1 audio feed which isn't the end of the world. But it removes my ability to use a Twitch Vod Track to avoid copyright strikes.

Do you often sing along to the music, is that an important part of your show? Because normally what you would put into the VOD track is only music. If that music is not properly synced to the rest, nobody would ever notice that, unless you sing along, because then (referring to my text diagram above) you'd have your voice in Primary Audio and the music in Secondary Audio and this wouldn't match.
Or do you play games with sound that could cause copyright issues, so that you need to put the game sound into the VOD track? Then ofc it's also a problem, because of the desync between Primary Video with the game visuals and Secondary Audio with the game sound.

**Comment by YorVeX** [comment] 2025-01-04 04:32
> Sounds like Beam needs multi-track support! 🗡️

Would have implemented that right from the start, but OBS is not giving plugins the other audio tracks, only track 1 😢

**Comment by YorVeX** [comment] 2025-01-04 05:39
Pretty much everything that is discussed here was my main motivation to create Beam BTW. I was exactly in the same situation and constantly resetting wasn't an option for me, as my stream had features that could cause a +500 ms jump in the delay even 10 seconds after I just did a reset.

While the technical background is complicated, the actual issue description is simple:

- If you like the majority of users have the default case of one video and audio feed that are kept together, you're good.
- Even if you have additional/separate audio or video feeds, but they don't need to be perfectly in sync (like music, or some random animation videos), also good.

But as soon as you need another separate feed synced to that OBS main A/V feed, there just is no simple solution, because that main OBS feed has a variable delay.

Since the variable delay is the root of all evil, that's exactly the part Beam solves, by providing a buffer with an artificial delay that is used to counter the fluctuations in the actual delay. Knowing that the OBS delay won't exceed 1200 ms (at least for me), I can set the buffer and delay to 1500 ms for some headroom. When the original feed has 0 ms delay, Beam will keep the full 1500 ms worth of frames buffered and ingests it to OBS with that delay. If the delay of the original feed goes up to 1200 ms, Beam will reduce its own buffer to 300 ms worth of frames, so you still end up with a total delay of 1500 ms on the receiver. That's really the only way I'm aware of that is capable of solving this.

**Comment by fzwoch** [comment] 2025-01-04 08:47
> > Sounds like Beam needs multi-track support! 🗡️
> 
> Would have implemented that right from the start, but OBS is not giving plugins the other audio tracks, only track 1 😢

https://docs.obsproject.com/reference-outputs#c.obs_output_info.raw_audio2 gives you a track index. So I would think it should get called for all tracks?

**Comment by fzwoch** [comment] 2025-01-04 19:14
For the record.. it works fine to transmit multi channel audio - but a source cannot send multiple tracks back to OBS. :sadge:

**Comment by YorVeX** [comment] 2025-01-04 22:00
> For the record.. it works fine to transmit multi channel audio - but a source cannot send multiple tracks back to OBS. :sadge:

Yeah. Then this was the reason why I didn't bother to implement it. It wouldn't help with the desync issue - unless you mix the audio tracks before giving it to the receiver OBS, which would destroy the purpose of having it separate in the first place.
